### PR TITLE
Add Tenant Name Filter

### PR DESCRIPTION
**Pull request by cdpadilla42**
Adding a styled tenant name search component!

The search bar sends the query through url params, which are then parsed and passed into the Apollo query with the `name_contains` filter. Filter is removed when the clear button is pressed or when the user completely deletes the input field.

One possible future concern is that search here is case sensitive. It is possible to remove any casing on the client side, but the GraphQL filter `name_contains` is case sensitive.

### CODE REVIEW

**Comment by ryanrightmer** [comment]
@cdpadilla42 I haven't looked at this too closely yet, but is this almost ready for review? The code seems relatively complete

**Comment by cdpadilla42** [comment]
@ryanrightmer Pretty much there! I'll clear out the issues that are keeping this from passing it's checks then it should be ready for review.

**Comment by cdpadilla42** [comment]
@ryanrightmer All set! 👌

**Review by SamPotasz — COMMENTED** [review]
looks good to me, but I don't know enough to feel comfortable officially approving any PRs yet 👍🏻

**Comment by ryanrightmer** [comment]
@cdpadilla42 I'll take a look at this tonight.

**Review by ryanrightmer — CHANGES_REQUESTED** [review]
I really like this. Only one comment: when I hit enter, it wipes the search, which I imagine would surprise a user. Can you capture that to submit the search instead?

**Comment by cdpadilla42** [comment]
Thanks for catching that! I'll fix that up.

**Review by ryanrightmer — APPROVED** [review]
Looks great!

**Pull request merged**
